// Code generated by MockGen. DO NOT EDIT.
// Source: IExtractor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	interfaces "grgd/interfaces"
	reflect "reflect"
)

// MockIExtractor is a mock of IExtractor interface
type MockIExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockIExtractorMockRecorder
}

// MockIExtractorMockRecorder is the mock recorder for MockIExtractor
type MockIExtractorMockRecorder struct {
	mock *MockIExtractor
}

// NewMockIExtractor creates a new mock instance
func NewMockIExtractor(ctrl *gomock.Controller) *MockIExtractor {
	mock := &MockIExtractor{ctrl: ctrl}
	mock.recorder = &MockIExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIExtractor) EXPECT() *MockIExtractorMockRecorder {
	return m.recorder
}

// GetCore mocks base method
func (m *MockIExtractor) GetCore(i interface{}) interfaces.ICore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCore", i)
	ret0, _ := ret[0].(interfaces.ICore)
	return ret0
}

// GetCore indicates an expected call of GetCore
func (mr *MockIExtractorMockRecorder) GetCore(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCore", reflect.TypeOf((*MockIExtractor)(nil).GetCore), i)
}

// GetMetadata mocks base method
func (m_2 *MockIExtractor) GetMetadata(m map[string]interface{}, key string, container interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "GetMetadata", m, key, container)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata
func (mr *MockIExtractorMockRecorder) GetMetadata(m, key, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockIExtractor)(nil).GetMetadata), m, key, container)
}

// GetMetadataFatal mocks base method
func (m_2 *MockIExtractor) GetMetadataFatal(m map[string]interface{}, key string, container interface{}) {
	m_2.ctrl.T.Helper()
	m_2.ctrl.Call(m_2, "GetMetadataFatal", m, key, container)
}

// GetMetadataFatal indicates an expected call of GetMetadataFatal
func (mr *MockIExtractorMockRecorder) GetMetadataFatal(m, key, container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataFatal", reflect.TypeOf((*MockIExtractor)(nil).GetMetadataFatal), m, key, container)
}
