// Code generated by MockGen. DO NOT EDIT.
// Source: ICore.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/gregod-com/grgd/interfaces"
	grgdplugincontracts "github.com/gregod-com/grgdplugincontracts"
	reflect "reflect"
	time "time"
)

// MockICore is a mock of ICore interface
type MockICore struct {
	ctrl     *gomock.Controller
	recorder *MockICoreMockRecorder
}

// MockICoreMockRecorder is the mock recorder for MockICore
type MockICoreMockRecorder struct {
	mock *MockICore
}

// NewMockICore creates a new mock instance
func NewMockICore(ctrl *gomock.Controller) *MockICore {
	mock := &MockICore{ctrl: ctrl}
	mock.recorder = &MockICoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockICore) EXPECT() *MockICoreMockRecorder {
	return m.recorder
}

// GetStartTime mocks base method
func (m *MockICore) GetStartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetStartTime indicates an expected call of GetStartTime
func (mr *MockICoreMockRecorder) GetStartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStartTime", reflect.TypeOf((*MockICore)(nil).GetStartTime))
}

// GetLogger mocks base method
func (m *MockICore) GetLogger() interfaces.ILogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(interfaces.ILogger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger
func (mr *MockICoreMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockICore)(nil).GetLogger))
}

// GetUI mocks base method
func (m *MockICore) GetUI() grgdplugincontracts.IUIPlugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUI")
	ret0, _ := ret[0].(grgdplugincontracts.IUIPlugin)
	return ret0
}

// GetUI indicates an expected call of GetUI
func (mr *MockICoreMockRecorder) GetUI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUI", reflect.TypeOf((*MockICore)(nil).GetUI))
}

// GetConfig mocks base method
func (m *MockICore) GetConfig() interfaces.IConfigObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(interfaces.IConfigObject)
	return ret0
}

// GetConfig indicates an expected call of GetConfig
func (mr *MockICoreMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockICore)(nil).GetConfig))
}

// GetHelper mocks base method
func (m *MockICore) GetHelper() interfaces.IHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelper")
	ret0, _ := ret[0].(interfaces.IHelper)
	return ret0
}

// GetHelper indicates an expected call of GetHelper
func (mr *MockICoreMockRecorder) GetHelper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelper", reflect.TypeOf((*MockICore)(nil).GetHelper))
}

// GetCMDPlugins mocks base method
func (m *MockICore) GetCMDPlugins() []grgdplugincontracts.ICMDPlugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCMDPlugins")
	ret0, _ := ret[0].([]grgdplugincontracts.ICMDPlugin)
	return ret0
}

// GetCMDPlugins indicates an expected call of GetCMDPlugins
func (mr *MockICoreMockRecorder) GetCMDPlugins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCMDPlugins", reflect.TypeOf((*MockICore)(nil).GetCMDPlugins))
}

// GetFileSystemManipulator mocks base method
func (m *MockICore) GetFileSystemManipulator() interfaces.IFileSystemManipulator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileSystemManipulator")
	ret0, _ := ret[0].(interfaces.IFileSystemManipulator)
	return ret0
}

// GetFileSystemManipulator indicates an expected call of GetFileSystemManipulator
func (mr *MockICoreMockRecorder) GetFileSystemManipulator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSystemManipulator", reflect.TypeOf((*MockICore)(nil).GetFileSystemManipulator))
}

// Get mocks base method
func (m *MockICore) Get(i interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockICoreMockRecorder) Get(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockICore)(nil).Get), i)
}
